# NodeJS Version 22
FROM node:22

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN pnpm install --legacy-peer-deps

# Set Env
ENV NODE_ENV development

EXPOSE 3000

# Cmd script
CMD ["pnpm", "run", "dev"]

